### ISSUE TITLE
brush/brush.info:brush_version=1.x-1.1 (should be 1.3)

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drop#9]
Version info isn't updating automagically?  Or maybe it's manual?  In any event it’s off ;)

Best,
Michael

```
inetd@srv10 [/home/common/bin]# wget https://github.com/backdrop-contrib/brush/archive/1.x-1.3.tar.gz

inetd@srv10 [/home/common/bin]# tar -zxf 1.x-1.3.tar.gz

inetd@srv10 [/home/common/bin]# brush status
 PHP configuration   :  /opt/cpanel/ea-php73/root/etc/php.ini
 Brush script        :  /usr/local/bin/php /home/common/bin/brush/brush.php --php='/usr/local/bin/php'
 Brush version       :  1.x-1.1
 Brush alias files   :  /home/common/bin/brush/includes/../mysite.aliases.brushrc.php

inetd@srv10 [/home/common/bin]# grep -ir '1.x-1.1' brush
brush/brush.info:brush_version=1.x-1.1

```

**Comment by ghost** [comment]
Hi Alan,

Well...  I did a fix (pull request), but I'm not really understanding github's way of Linking it to this Issue.  Okay, if I'm reading the doc's right I can't (don't have privileges)?  But it's showing up in the Pull Request tab, so....

Mostly, I'm just doing a test on how to submit patches/fixes, so did I do the right thing(s)?  Anything I miss?

Best,
Michael

PS:
Because manually changing the version would really suck, I did a Goggle search: "github insert project version"

Results in:
https://github.com/conventional-changelog/standard-version/issues/324
-and-
https://gist.github.com/nzakas/7633640

So maybe there's a code way to do this?

**Comment by alanmels** [comment]
Michael,

Thanks for the PR. With limited time I have for this project I really do appreciate other users to start adding PRs. Please note your PR (https://github.com/backdrop-contrib/brush/pull/11) has been merged, so if you pull the dev version then you can see the change is reflected. However, IMO we need to find some way to make version change in the info file automated. I will look into this some time later.

As for your question, just put the link to a respective issue in the subject of PR, for example, if you had put "Resolves https://github.com/backdrop-contrib/brush/issues/9" instead of "Update brush.info", then the PR would be automatically connected to this page.
